### ISSUE TITLE
Overnight server error

### ISSUE THREAD

**Issue by generica** [VPAC/patchman#3]
Cron root@help /var/lib/patchman/sbin/patchman-cli -d -U -c -r -p (failed)

Traceback (most recent call last):
  File "/var/lib/patchman/sbin/patchman-cli", line 728, in <module>
    process_reports(args.host)
  File "/var/lib/patchman/sbin/patchman-cli", line 669, in process_reports
    report.process()
  File "/usr/local/lib/python2.6/dist-packages/patchman/reports/models.py", line 118, in process
    process_repos(report=self, host=host)
  File "/usr/local/lib/python2.6/dist-packages/patchman/reports/utils.py", line 34, in process_repos
    hostrepo, c = HostRepo.objects.get_or_create(host=host, repo=repository, priority=priority, enabled=True)
  File "/usr/lib/pymodules/python2.6/django/db/models/manager.py", line 135, in get_or_create
    return self.get_query_set().get_or_create(**kwargs)
  File "/usr/lib/pymodules/python2.6/django/db/models/query.py", line 366, in get_or_create
    return self.get(**kwargs), False
  File "/usr/lib/pymodules/python2.6/django/db/models/query.py", line 333, in get
    clone = self.filter(_args, *_kwargs)
  File "/usr/lib/pymodules/python2.6/django/db/models/query.py", line 550, in filter
    return self._filter_or_exclude(False, _args, *_kwargs)
  File "/usr/lib/pymodules/python2.6/django/db/models/query.py", line 568, in _filter_or_exclude
    clone.query.add_q(Q(_args, *_kwargs))
  File "/usr/lib/pymodules/python2.6/django/db/models/sql/query.py", line 1128, in add_q
    can_reuse=used_aliases)
  File "/usr/lib/pymodules/python2.6/django/db/models/sql/query.py", line 1071, in add_filter
    connector)
  File "/usr/lib/pymodules/python2.6/django/db/models/sql/where.py", line 66, in add
    value = obj.prepare(lookup_type, value)
  File "/usr/lib/pymodules/python2.6/django/db/models/sql/where.py", line 299, in prepare
    return self.field.get_prep_lookup(lookup_type, value)
  File "/usr/lib/pymodules/python2.6/django/db/models/fields/__init__.py", line 874, in get_prep_lookup
    return super(IntegerField, self).get_prep_lookup(lookup_type, value)
  File "/usr/lib/pymodules/python2.6/django/db/models/fields/**init**.py", line 292, in get_prep_lookup
    return self.get_prep_value(value)
  File "/usr/lib/pymodules/python2.6/django/db/models/fields/**init**.py", line 868, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'http://10.0.100.1/install/centos5.7/x86_64/updates/x86_64'

**Comment by furlongm** [comment]
Can you ensure that this host received the updated patchman-client from puppet? Check the failed reports to find out which host it is.

**Comment by generica** [comment]
Yep, forgot two hosts that don't get the client via puppet
